### ISSUE TITLE
Exact sampling leads to wrong simulation result

### ISSUE THREAD

**Issue by schmitts** [arbor-sim/arbor#2083] opened 2023-01-25 09:31 UTC
I'm on `eee16c7898db2232340e350819a75f050c143e28` and use the attached mechanism and script.

The mechanism `constant_inject` injects constantly to an ion concentration.
The time course of the concentration depends on which sampling policy I use to probe it.
The expected result is a constant increase, however, there is a change in slope when using `exact` sampling.

Adding some debug output might hint to the problem:

```cpp
diff --git a/arbor/fvm_lowered_cell_impl.hpp b/arbor/fvm_lowered_cell_impl.hpp
index b3d09765..4fa38676 100644
--- a/arbor/fvm_lowered_cell_impl.hpp
+++ b/arbor/fvm_lowered_cell_impl.hpp
@@ -266,6 +266,7 @@ fvm_integration_result fvm_lowered_cell_impl<Backend>::integrate(
 
         state_->update_time_to(dt_max, tfinal);
         events.event_time_if_before(state_->time_to);
+        std::cerr << *state_ << '\n';
         state_->set_dt();
         PL();
```

For `exact`:
```
time_to      0.1
time_to      0.2
time_to      0.3
time_to      0.4
time_to      0.5
time_to      0.6
time_to      0.6
time_to      0.7
time_to      0.8
time_to      0.9
time_to      1
```

For `lax`:
```
time_to      0.1
time_to      0.2
time_to      0.3
time_to      0.4
time_to      0.5
time_to      0.6
time_to      0.7
time_to      0.8
time_to      0.9
time_to      1
time_to      1
```

In the case of `exact` sampling, the timestep 0.6 appears twice which is the time where the deviation occurs (see plot).

[constant_inject.mod.gz](https://github.com/arbor-sim/arbor/files/10497831/constant_inject.mod.gz)
[constant_inject.py.gz](https://github.com/arbor-sim/arbor/files/10497833/constant_inject.py.gz)

![constant_inject](https://user-images.githubusercontent.com/1502412/214527649-121e7b36-30c2-431e-85ff-a73d01406c32.png)

**Comment by thorstenhater** [comment] 2023-01-25 12:28
That's very unfortunate. Thanks for reporting.

**Comment by thorstenhater** [comment] 2023-01-25 12:34
From my current view this occurs as we execute the `Xd` modifying code twice. For other quantities than `Xd` this doesn't hurt the outcomes as we reset them at every timestep.

I _think_ it's a bug to do two timesteps here and I _think_ I remember this will incidentally be resolved by @boeschf 's
fixed-dt #2053.

**Comment by schmitts** [comment] 2023-01-25 16:01
What can we do for #2053 to advance? I also found issues with `lax` sampling that do not occur with #2053.

**Comment by thorstenhater** [comment] 2023-01-25 19:20
Issues related to diffusion, or other parts of the code?

**Comment by boeschf** [comment] 2023-01-25 21:04
@schmitts: #2053  is coming soon . I am working on fixing a performance regression on GPUs for high event loads. Should be ready for review by next week.

**Comment by schmitts** [comment] 2023-01-26 10:17
> Issues related to diffusion, or other parts of the code?

Yes, related to diffusion. When a synaptic event is triggered (by an input spike), the diffusion is erroneous increased. It looks similar to the doubled integration effect when using `exact` sampling. Do you want the details and the code or do we say "won't fix" because the problem vanishes in the new regular `dt` integration scheme?

**Comment by thorstenhater** [comment] 2023-01-26 10:20
Yes, it is. An event at `t` 'splits' the `dt` interval into `n dt <= t <= (n+1) dt`. If `t` is not a multiple of `dt`, you'll get an extra step. That's not an issue if your injection is following an ODE, but if it's at flat value...

**Comment by thorstenhater** [comment] 2023-01-26 10:23
So, I wouldn't say 'wont-fix', but 'postpone after `fixed-dt`' ;) Did you test these case with `fixed-dt` already, if not do you want to? Regardless, yes, I do want the examples as regression tests.

**Comment by schmitts** [comment] 2023-01-26 10:35
The overshoots at times 5, 7 and 9 should not be present.

![diffusion_protein](https://user-images.githubusercontent.com/1502412/214814864-83ede749-a096-48df-89b0-288bdddd0143.png)
[diffusion_protein.py.gz](https://github.com/arbor-sim/arbor/files/10508361/diffusion_protein.py.gz)
[dummy_synapse.mod.gz](https://github.com/arbor-sim/arbor/files/10508364/dummy_synapse.mod.gz)
[dummy_neuron.mod.gz](https://github.com/arbor-sim/arbor/files/10508365/dummy_neuron.mod.gz)

**Comment by thorstenhater** [comment] 2023-01-26 10:36
And these are correlated with incoming events?

**Comment by schmitts** [comment] 2023-01-26 10:37
> And these are correlated with incoming events?

Yes

**Comment by jlubo** [comment] 2023-04-05 19:59
I guess this can be closed, since the PR [#2053](https://github.com/arbor-sim/arbor/pull/2053) has been merged today?

**Comment by thorstenhater** [comment] 2023-04-06 12:19
Does it persist, though?

**Comment by jlubo** [comment] 2023-04-06 13:59
Seems to be solved, considering the previous test simulations (with commit 2ec4db34bdc67ddb9d2b16b1946ee40d974eb413).
![fixed_dt](https://user-images.githubusercontent.com/33398515/230399840-3996b819-4ae8-4f82-b2df-4c4085a8385b.png)

![diffusion_protein](https://user-images.githubusercontent.com/33398515/230399792-d927c0aa-4f4a-4516-8407-da7d31f7b152.png)

**Closed by jlubo** 2023-04-06 13:59 UTC
Labels: bug
