### ISSUE TITLE
Multi-GPU cell groups for gap-junction networks without waveform relaxation.

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1422] opened 2021-03-09 14:57 UTC
Large gap junction networks are currently constrained by the memory available to a single cell group. This memory could be increased in the case of multi-GPU nodes, if a cell group could be partitioned across multiple GPUs.

Random observations:
* This is a bit like NEURON multisplit in conception, which may be a terrible idea for Arbor.
* The key complication (after resource wrangling) would be the voltage solver. If cells are not split across GPUs, this would come down to the GPU-GPU communication of gap junction contributions each time step.

The motivation for this comes from the prospect of large (> 1e6 neuron) models of the inferior olive.

**Comment by bcumming** [comment] 2021-03-12 07:49
There are two ways to achieve this:
1. cells connected via gap-junctions are in the cell group, and the cell group is split over multiple GPUs, with the task that integrates over keeping them in sync.
2. allow connected cells to be in different cell groups that are in different MPI ranks, and find a way to advance each of these groups  one step at a time with MPI communication of voltages at each step.

Approach 1. would be the simplest to implement, and would provide some insight into performance costs of this approach. However it has some drawbacks, the main one of which is
* it only scales to the number of  GPUs on a node, and only on nodes where more than one GPU is permitted per rank in an MPI applications (i.e. it likely won't work on Cray Shasta systems). So it won't be a viable solution for strong scaling large systems with many gap junctions.

Still, approach 1 is the most interesting option to try first, to explore non relaxed methods, before thinking about option 2, which is not attractive for the following reasons:
* synchronisation of cell groups connected via gap junction over multiple MPI ranks will require _a lot_ of refactoring and add inhernent complexity of time stepping.
* performance would take a massive hit. The synchonization overheads, inability to hide kernel latencies, communication latencies, etc on every time step.
* locking time steps of connected cells in different cell groups with our time step binning approach will be tricksy.

**Comment by max9901** [comment] 2022-01-27 10:37
Duplicate of #1766

**Closed by max9901** 2022-01-27 10:37 UTC
Labels: enhancement, AEP, gpu, Project: Arborio
