### ISSUE TITLE
I'd like to switch from NEURON to Arbor

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#911] opened 2019-12-02 15:36 UTC
First of all, a big congratulations on such clean and consequently applied design principles! Your documentation already is amazing and I look forward to designing recipes in Arbor :)

However, when dealing with 15+ years of accumulated NEURON models it's hard to convince people to make the step to change, even though they are infuriated daily by the messy incomprehensible state and inner workings of NEURON.

Are there any arguments to convince my lab partners that modelling in Arbor and making the switch is going to be less daunting than they think? For example are there easy to use replacements for the neuron GUI they're used to? Can the MOD files be transpiled into Arbor mechanisms? Can they do the same kind of BluePyOpt operations on multicompartmental Arbor cell models?

**Comment by bcumming** [comment] 2019-12-02 16:10
Thank you!

In my opinion, it is the 15 years of accumulated NEURON models that make it difficult to change. NEURON expects models to be described using _code_, either hoc or Python, not using a prescriptive description of the model. This has the benefit of allowing users to use Turing complete languages to write pretty much anything they want, and use NMODL VERBATIM blocks to hack features into the back end, if they are brave enough.

This also means that by design separate the model description is not separated from the source code that generates it. The combined hoc, python and NMODL contain not only model descriptions, but 15 years of institutional knowledge, tightly coupled together. Honestly, there is no easy fix for this. It requires a large effort to move models over time.

The best solution is to develop Arbor to the point where the ease of use, model features and performance benefits become irresistible. That and being able to get time on the next round of massive supercomputers that will be set up in Europe over the next 2 years, which will require GPU support. 

Regarding your questions:
  * We don't have a GUI planned. Our efforts have been on the back end library, and recently the Python wrapper.
  * We support NMODL files! We actually support many many NMODL features, though there are some small differences to watch out for (e.g. we treat ion species in a sane and consistent manner... which might take a while for NEURON users to get used to).
  * We haven't tested parameter optimization with BluePyOpt, but in principle it should be straightforward using BluePyOpt's json interface.

We are currently working hard to make "single cell workflows", i.e. defining cell morphologies, placing mechanisms on the cell, attaching probes/stims, then running a nice experience. This will be ready for the HBP summit in Febrary. From that point on, we can then look at parameter optimization, and some visual tools to make it easy to interact with these models.

**Comment by Helveg** [comment] 2019-12-02 16:14
Ok, thanks for the quick answer! Good luck with your endeavours :)

**Comment by bcumming** [comment] 2019-12-03 08:17
@Helveg, we would be happy to help you get started with Arbor. Do you have a model that you would like to run in Arbor, to demonstrate to your colleagues?

**Comment by Helveg** [comment] 2019-12-03 09:25
I have 5 detailed cable cell models for the cerebellum (ASC/SWC) with electrophysiological properties (NMODL) and I've developed a software framework that can place them in a simulation volume, tell which ones are supposed to be connected and has an interface available for simulators to easily descripe the model to different simulators. It's already interfaced with NEST but NEURON isn't playing ball ;) I'm rejoiced because in principle your design desicions should make describing my simulation to Arbor a breeze.

I'll try to use the examples and documentation available to me to see how far I get on the recipe.

For the cable cells I have a `.asc` file or `.swc` file and a 15 year old messy description template in python/neuron carefully adapted to this celltype where dictionaries with single elements, 2 input devices connected to eachother and other "intricacies" need to be carefully catered to in order for NEURON not to freak out ;) What's my next step there?

**Comment by bcumming** [comment] 2019-12-03 10:11
We read SWC files, and a comprehensive set of NMODL features.

It is the python/NEURON template that will be where all the work is! The biggest challenge that we have found porting such "single cell" hoc/python _templates_ is that code that describes the "what" (e.g. I want this ion channel on all dendrites with radius less than 3 um) and the "how" (I am going to walk the tree and store the dendrite indexes in a dictionary).

The first step is to pick the simplest of your 5 cells, and write down "what" that template is describing, not "how" it is doing it. That should reduce 500 lines of hoc to a surprisingly short description.

e.g.: 
region "soma": has tag 1 in swc file
region "axon": has tag 2 in swc file
region "dendrites": has tag 3 in swc file
region "hillock": the first 60 um of region "axon" after region "soma"
region "axon-rest": part of region "axon" not in region "hillock"
locations "soma_center": centre of region "soma"
locations "stimsite": centre of the proximal branch of region "dendrites"
... etc ...

Then define the mechanisms you want to use
```
hh      = mechanism("hh")                               // hh with default parameters
hh_fast = mechanism("hh", {"gk_bar": 0.1})      // hh with dictionary of parameter values
stim    = iclamp(tstart=10ms, tend=30ms, current=0.1nA)
spike_det= detector(threshold=-10mV)
... etc ...
```

Then describe what goes where:

`hh` goes on region "dendrite"
`hh_fast` goes on region "hillock"
`stim` goes on locations "stimsite"
`spike_det` goes on locations "soma_center"
... etc ...

Then you will have pseudo-code description of what Arbor requires! Note that you never refer to compartments, and you don't iterate over branches. It is a flat description, and discretization into compartments happens at a later point (you can just let Arbor handle discretization, or you can have full control).

**Comment by Helveg** [comment] 2019-12-03 11:12
That's creepy... To rework things into something more optimal, I've made a packet manager for the mod files (handles compilation and naming conflicts, insertion of attributes, ...) and it works exactly like your `mechanism` call. On top of that I've been reworking the model templates ... and they too do exactly as you describe. So it seems that the switch to Arbor is going to be quite easy

Here's a Golgi cell, parameters redacted because I'm not sure it's published ;)

```
class GolgiCell(NeuronModel):
    morphologies = ['pair-140514-C2-1_split_1.asc']

    section_types = {
        "soma": {
            "mechanisms": ['Leak', 'Nav1_6',],
            "attributes": {
                "Ra": 122, "cm": 1, "gkbar_Nav1_6": ...
            }
        },
        "dendrites": {
            "mechanisms": [], "attributes": {}
        },
        "basal_dendrites": {
            "mechanisms": ['Leak','Nav1_6','Kv1_1'],
            "attributes": {
                "Ra": 122, "cm": 3, ...
            }
        },
        "apical_dendrites": {
            ...
        },
        "axon": {
            ...
        },
        "axon_initial_segment": {
            ...
        }
    }
```

So that seems to solve the description part, I could add a method `to_arbor()` to the base class of my models that would return whatever object description Arbor requires. Or you could go hella pythonic and look for a magic method `__arbor__` on my object :)

The only thing I'm unclear about is how to translate this to Arbor:

> region "soma": has tag 1 in swc file
> region "axon": has tag 2 in swc file
> region "dendrites": has tag 3 in swc file
> region "hillock": the first 60 um of region "axon" after region "soma"
> region "axon-rest": part of region "axon" not in region "hillock"
> locations "soma_center": centre of region "soma"
> locations "stimsite": centre of the proximal branch of region "dendrites"

**Comment by bcumming** [comment] 2019-12-03 12:25
Ah, `Nav1_6`, we know that mechanism... don't worry, we support it!

In NEURON, when a cell morphology is loaded, some regions are typically auto-populated on a cell (soma, axon, apical_dendrites, basal_dendrites, dendrites). In an SWC file, these are determined by a numeric tag on each sample point: 1 for soma, 2 for axon, ... etc.

Then if you want to create more specialized regions (e.g. `axon_initial_segment`), you have to loop over the segments in the cell (or in `axon`) and manually create the region "algorithmically".

In Arbor we provide a simple DSL for doing this:

```
label('soma', '(tag 1)')
label('axon', '(tag 2)')
label('basal_dendrite', '(tag 3)')
label('apical_dendrite', '(tag 4)')
label('dendrites', '(join (region "basal_dendrite") (region "apical_dendrite"))'
... etc
```

In our experience, it is creating these regions and painting mechanisms on them that (a) generates the most code in model descriptions (b) is the source of most bugs in model descriptions.

**Comment by bcumming** [comment] 2019-12-03 12:27
Send me an email if you want organise a skype call (you can find it on the cscs staff about page...)
https://www.cscs.ch/about/staff/

**Comment by Helveg** [comment] 2019-12-03 12:42
Ok it seems like the quality of this DSL is going to determine a lot then. Is there a full description of it somewhere?

**Comment by bcumming** [comment] 2019-12-03 12:49
Yes, the quality will make a difference.
At the moment there are no docs, which will be released with the Python wrapper.
We don't have that many expression types in the DSL yet: they will be developed with our users, but the idea is to keep it as small as possible, and only add expression types when they are needed.

**Comment by SteMasoli** [comment] 2019-12-07 08:11
@bcumming @Helveg 
> The first step is to pick the simplest of your 5 cells, and write down "what" that template is describing, not "how" it is doing it. That should reduce 500 lines of hoc to a surprisingly short description.

I think I know a thing or two about these specific models. I can help with that. ;)

**Comment by bcumming** [comment] 2020-02-04 15:31
We have merged a workable Python front-end for Arbor in #948.
With this, and an example of using it for one of your models, I think we can close this issue.

**Closed by bcumming** 2020-02-04 15:31 UTC
