### ISSUE TITLE
Issues with using a custom catalogue on GPU 

### ISSUE THREAD

**Issue by schmitts** [arbor-sim/arbor#2056] opened 2022-12-05 13:27 UTC
Loading a custom catalogue on GPU instead of using the default catalogue makes the simulation very slow. Also, no GPU utilization is registered (`nvtop`/`nvidia-smi`). Here's a recipe to reproduce. Case D is the problematic one.

```
git clone ssh://github.com/arbor-sim/arbor.git
cd arbor
git checkout 16273024513ddbe2cad34345c91932e57dc79598
git submodule update --init --recursive

mkdir build
cd build
cmake -DARB_GPU=cuda -DARB_WITH_PYTHON=ON -DARB_USE_BUNDLED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$(readlink -f ~/local) ..
make install
export PATH=$(readlink -f ~/local/bin):$PATH
export PYTHONPATH=$(readlink -f ~/local/lib/python3.8/site-packages):$PYTHONPATH
export LD_LIBRARY_PATH=$(readlink -f ~/local/lib)

cd ../python/examples
arbor-build-catalogue custom ../../mechanisms/default

patch << 'EOF'
diff --git a/python/example/network_ring_gpu.py b/python/example/network_ring_gpu.py
old mode 100644
new mode 100755
index 22a9b43..3848775
--- a/python/example/network_ring_gpu.py
+++ b/python/example/network_ring_gpu.py
@@ -1,6 +1,10 @@
 #!/usr/bin/env python3
 # This script is included in documentation. Adapt line numbers if touched.
 
+import os
+import sys
+from distutils.util import strtobool
+
 import arbor
 import pandas  # You may have to pip install these
 import seaborn  # You may have to pip install these
@@ -82,6 +86,11 @@ class ring_recipe(arbor.recipe):
         arbor.recipe.__init__(self)
         self.ncells = ncells
         self.props = arbor.neuron_cable_properties()
+        if strtobool(os.getenv("ARBOR_USE_CUSTOM_CATALOGUE", "false")):
+            print("Using custom catalogue")
+            self.props.catalogue = arbor.load_catalogue("./custom-catalogue.so")
+        else:
+            print("Using default catalogue")
 
     # (6) The num_cells method that returns the total number of cells in the model
     # must be implemented.
@@ -123,7 +132,14 @@ class ring_recipe(arbor.recipe):
 # (11) Set up the hardware context
 # gpu_id set to None will not use a GPU.
 # gpu_id=0 instructs Arbor to the first GPU present in your system
-context = arbor.context(threads="avail_threads", gpu_id=None)
+
+try:
+    gpu_id = int(os.getenv("ARBOR_GPU_ID"))
+except ValueError as e:
+    print("Cannot set gpu_id, setting to None")
+    gpu_id = None
+
+context = arbor.context(threads="avail_threads", gpu_id=gpu_id)
 print(context)
 
 # (12) Set up and start the meter manager
@@ -163,9 +179,12 @@ meters.checkpoint("simulation-run", context)
 print(f"{arbor.meter_report(meters, context)}")
 
 # Print spike times
+"""
 print("spikes:")
 for sp in sim.spikes():
     print(" ", sp)
+"""
+sys.exit(0)
 
 # Plot the recorded voltages over time.
 print("Plotting results ...")
EOF

# A
time ARBOR_USE_CUSTOM_CATALOGUE=no ARBOR_GPU_ID=none python3 network_ring_gpu.py
# B
time ARBOR_USE_CUSTOM_CATALOGUE=yes ARBOR_GPU_ID=none python3 network_ring_gpu.py
# C
time ARBOR_USE_CUSTOM_CATALOGUE=no ARBOR_GPU_ID=0 python3 network_ring_gpu.py
# D
time ARBOR_USE_CUSTOM_CATALOGUE=yes ARBOR_GPU_ID=0 python3 network_ring_gpu.py
```

**Comment by schmitts** [comment] 2022-12-14 12:39
cuda mechanism is executed, but takes 2000 times longer.

```
from custom catalogue, pas_gpu computing currents
it took: 64592 us

from default catalogue, pas_gpu computing currents
it took: 30 us
```

```cpp
void mechanism_pas_gpu_compute_currents_(arb_mechanism_ppack* p) {
    auto n = p->width;
    unsigned block_dim = 128;
    unsigned grid_dim = ::arb::gpu::impl::block_count(n, block_dim);
    std::cerr << "from default catalogue, pas_gpu computing currents\n";
    std::chrono::steady_clock::time_point begin = std::chrono::steady_clock::now();
    compute_currents<<<grid_dim, block_dim>>>(*p);
    std::cerr << "it took: " << std::chrono::duration_cast<std::chrono::microseconds>(std::chrono::steady_clock::now() - begin).count() << " us\n";
}
```

**Comment by thorstenhater** [comment] 2023-01-24 07:52
@schmitts I remember an offline conversion where you said you couldn't reproduce this anymore?
If so, please close this.

**Comment by schmitts** [comment] 2023-01-24 08:08
I can reproduce it, but only on the Heidelberg GPU system, not on the GWDG system.

**Comment by thorstenhater** [comment] 2023-09-05 16:03
I am closing this since we cannot reproduce. Please reopen on occasion.

**Closed by thorstenhater** 2023-09-05 16:03 UTC
Labels: bug
