### ISSUE TITLE
Random123 as a submodule 

### ISSUE THREAD

**Issue by max9901** [arbor-sim/arbor#1778] opened 2021-11-29 10:34 UTC
## Goal
Be able to compile random123 on GPU implementations + make them available for users that custom compile their catalogs.

## Implementation
Add the following sub-module and try to get the source code working with the HIP languages. (PR request to the original repo) 
https://github.com/DEShawResearch/random123 

Change the Cmake build to expose the random123 Header files to the user.

**Comment by brenthuisman** [comment] 2022-02-16 10:35
Duplicate of #1731

**Comment by brenthuisman** [comment] 2022-08-02 12:15
Was closed with #1872

**Closed by brenthuisman** 2022-08-02 12:15 UTC
Labels: enhancement, AEP, Project: Arborio
