### ISSUE TITLE
domain_decomposition::gid_domain very slow for big simulations

### ISSUE THREAD

**Issue by noraabiakar** [arbor-sim/arbor#869] opened 2019-09-20 09:24 UTC
`domain_decomposition::gid_domain` explodes the `model-init` time of a simulation. This is most likely because of the extra checks we need to do to support gap-junctions.

**Comment by halfflat** [comment] 2019-12-18 15:40
Issue #909 is a dupe of this issue; so also fixed by #910.

**Closed by halfflat** 2019-12-18 15:40 UTC
Labels: optimization
